{% set name = "cythonbuilder" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cythonbuilder-{{ version }}.tar.gz
  sha256: ecaf7c98f743a4e2831d893d550400e32cbac3f964b8ea3e3a37f80350d707d2

build:
  noarch: python
  entry_points:
    - cythonbuilder=cythonbuilder.cli:app
    - cybuilder=cythonbuilder.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9, <4.0
    - poetry
    - poetry-core
    - pip
  run:
    - python >=3.9, <4.0
    - cython >=0.29.28, <0.30.0
    - typer >=0.7.0, <0.8.0
    - coloredlogs

test:
  imports:
    - cythonbuilder
  commands:
    - pip check
    - cythonbuilder --help
    - cybuilder --help
  requires:
    - pip

about:
  home: https://github.com/mike-huls/cythonbuilder
  summary: CythonBuilder; automated compiling and packaging of Cython code
  dev_url: https://github.com/mike-huls/cythonbuilder/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
