{% set name = "cythonbuilder" %}
{% set version = "0.1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cythonbuilder-{{ version }}.tar.gz
  sha256: 5121abc6643746c62bf256f5068b378b0f29301343a5ce9fedd74f1cd8f6724e

build:
  noarch: python
  entry_points:
    - cythonbuilder=cythonbuilder.cli:app
    - cybuilder=cythonbuilder.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - cython >=0.29.28, <0.30.0
    - typer >=0.7.0, <0.8.0
    - coloredlogs

test:
  imports:
    - cythonbuilder
  commands:
    - pip check
    - cythonbuilder --help
    - cybuilder --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mike-huls/cythonbuilder
  summary: CythonBuilder; automated compiling and packaging of Cython code
  dev_url: https://github.com/mike-huls/cythonbuilder/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
