schema_version: 1

context:
  name: cythonbuilder
  version: 0.1.22

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cythonbuilder-${{ version }}.tar.gz
  sha256: 5121abc6643746c62bf256f5068b378b0f29301343a5ce9fedd74f1cd8f6724e

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cythonbuilder=cythonbuilder.cli:app
      - cybuilder=cythonbuilder.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry
    - poetry-core
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - cython >=0.29.28,<0.30.0
    - typer >=0.7.0,<0.8.0
    - click <8.2
    - coloredlogs

tests:
  - python:
      imports:
        - cythonbuilder
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - cythonbuilder --help
      - cybuilder --help

about:
  summary: CythonBuilder; automated compiling and packaging of Cython code
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/mike-huls/cythonbuilder
  repository: https://github.com/mike-huls/cythonbuilder/

extra:
  recipe-maintainers:
    - pavelzw
